__title__ = 'sphinxcontrib-lpblocks'
__summary__ = 'Literate Programming with reStructuredText'
__url__ = 'https://github.com/rblack42/sphinxcontrib-lpblocks'
__pypi__ = 'http://pypi.python.org/pypi/sphinxcontrib-lpblocks'
__author__ = 'Roie R. Black'
__email__ = 'roie.black@gmail.com'
__license__ = 'BSD 3-Clause'
